name: Build and Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-gcc-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
    - name: Install prereq using conda
      run: |
        conda install -c conda-forge gobject-introspection pygobject python_abi=3.9=2_cp39 -y
        echo "$CONDA/bin" >> $GITHUB_PATH
    - name: Install prereq using pip
      run: |
        pip install -r requirements.txt
    - name: Install the package
      run: |
        python setup.py install
    - name: Install NumCosmo from conda-forge
      run: |
        conda install -c conda-forge numcosmo -y
    - name: Install cluster_toolkit from source
      run: |
        git clone https://github.com/tmcclintock/cluster_toolkit.git
        cd cluster_toolkit
        python setup.py install
    - name: Install CCL from source
      run: |
        conda install -c conda-forge cmake swig -y
        git clone https://github.com/LSSTDESC/CCL
        cd CCL
        python setup.py install
    - name: Run the unit tests
      run: |
        pip install pytest pytest-cov
        pytest tests/ --ignore=cluster_toolkit/tests --cov=clmm/
      env:
        DISPLAY: test
    - name: Install Sphinx prereq
      run: |
        conda install sphinx sphinx_rtd_theme nbconvert pandoc ipython ipython_genutils
    - name: Run the docs
      run: |
        make -C docs/ html
    - name: Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pip install coveralls
        coveralls --service=github
